### PR TITLE
Signing button handling and general app button styling

### PR DESCRIPTION
**Pull request by tkenakka**

### CODE REVIEW

**Comment by evidentti** [comment]
- On mobile sign item page one liner header is not centralised
- On desktop sign item page 'arrow left' should be replaced by 'home'
- Status and Kommentoi button have sharp corners like they are not part of any group.

**Comment by evidentti** [comment]
Approved

**Comment by tkenakka** [comment]
Review fixes and new improvements added, starting from 739ef16

**Comment by tkenakka** [comment]
Review fixes and new improvements added, starting from 739ef16

**Comment by evidentti** [comment]
LGTM

**Pull request merged**
